In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [46]:
def KernlPCA(train_x,test_x,n):
    from sklearn.decomposition import KernelPCA
    kpca = KernelPCA(n_components = n, kernel = 'rbf')
    train_x = kpca.fit_transform(train_x)
    test_x = kpca.transform(test_x)

    return train_x, test_x #lda_features

In [48]:
def split_scalar(indep_X,dep_Y):
        train_x, x_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        train_x = sc.fit_transform(train_x)
        test_x = sc.transform(x_test)    
        return train_x, test_x, y_train, y_test

In [50]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return classifier,Accuracy,report,X_test,y_test,cm

In [52]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return classifier,Accuracy,report,X_test,y_test,cm

In [54]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [56]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [58]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [60]:
def knn(X_train,y_train,X_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [62]:
def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion  = 'entropy',random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [64]:
def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [66]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['Kernal_PCA'],columns=['Logistic','SVMl','SVMNl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        # df.loc[row_indexer, "col"] = values
        dataframe.loc[idex,'Logistic']=acclog[number]
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMNl']=accsvmnl[number]
        dataframe.loc[idex,'KNN']=accknn[number]
        dataframe.loc[idex,'Navie']=accnav[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
        # print(dataframe)
        # dataframe['Logistic'][idex]=acclog[number]       
       # dataframe['SVMl'][idex]=accsvml[number]
        # dataframe['SVMnl'][idex]=accsvmnl[number]
        # dataframe['KNN'][idex]=accknn[number]
        # dataframe['Navie'][idex]=accnav[number]
        # dataframe['Decision'][idex]=accdes[number]
        # dataframe['Random'][idex]=accrf[number]
    return dataframe

In [68]:

# Importing the dataset
dataset = pd.read_csv('Wine.csv')
df2=dataset.copy()
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [70]:

df2 = pd.get_dummies(df2, drop_first=True)
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [72]:
X = df2.iloc[:, 0:13].values
Y = df2.iloc[:, 13].values

In [74]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [76]:
train_x, test_x, y_train, y_test=split_scalar(X,Y)

In [114]:
X_train, X_test=KernlPCA(train_x,test_x,3)       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [116]:
X_train

array([[ 0.45001125, -0.18011692,  0.02940191],
       [-0.50908921, -0.17708232, -0.14075832],
       [ 0.22912144,  0.22867988,  0.01404963],
       [-0.39094964, -0.22582842, -0.23094292],
       [ 0.45739253, -0.32875672,  0.19724109],
       [-0.43675638, -0.12253855, -0.24119887],
       [-0.53967332, -0.19740644, -0.09254141],
       [ 0.50825951, -0.18147683,  0.04087151],
       [-0.1118486 , -0.17184162,  0.15260004],
       [ 0.55606857, -0.06700944, -0.11394393],
       [-0.01355039,  0.54022571, -0.13836826],
       [-0.42978548, -0.38306705, -0.08532039],
       [-0.49513291, -0.18059311, -0.17500289],
       [ 0.15182197,  0.1525388 ,  0.23354878],
       [-0.52192518, -0.15006861,  0.16644382],
       [-0.50561246, -0.37856784, -0.02174234],
       [ 0.35296096,  0.02567942, -0.36760829],
       [-0.44906672, -0.03104355,  0.15803533],
       [-0.36025348,  0.01671017, -0.13225321],
       [ 0.11919057,  0.49980424, -0.32214736],
       [-0.33372931,  0.10295192, -0.26674112],
       [-0.54386092, -0.21635397, -0.21993241],
       [ 0.02921693,  0.27526187, -0.44824092],
       [ 0.48282336, -0.1913141 ,  0.19008928],
       [-0.06068507,  0.09749333, -0.22536264],
       [ 0.04933189, -0.0350719 ,  0.08817387],
       [-0.08620484,  0.0665331 ,  0.07840284],
       [ 0.15835435,  0.04037342, -0.01390874],
       [ 0.53810343, -0.31372704, -0.0197518 ],
       [ 0.17432859,  0.30986638,  0.30698837],
       [ 0.08610009, -0.03054339,  0.22989036],
       [-0.49111491, -0.26164078, -0.15146007],
       [-0.21026771, -0.21645138,  0.1355262 ],
       [ 0.02078209,  0.08450051,  0.08621753],
       [-0.01322928,  0.58081646,  0.05907467],
       [-0.04955616,  0.6228077 , -0.15746097],
       [-0.42722018, -0.3788513 ,  0.06860891],
       [-0.53796374, -0.10105614, -0.21387049],
       [ 0.34629598, -0.13102915, -0.15020917],
       [-0.4993845 , -0.35405864,  0.07124684],
       [-0.07581114,  0.55686687,  0.16151964],
       [-0.08547587,  0.35230315,  0.07146997],
       [-0.14212199,  0.18476349,  0.47125503],
       [ 0.03846012,  0.17417512,  0.22035246],
       [ 0.0185594 ,  0.03194148, -0.03795613],
       [ 0.53931463, -0.33500554, -0.01988074],
       [ 0.54402913, -0.25229784,  0.0236078 ],
       [ 0.12826896,  0.52488451, -0.19868454],
       [ 0.32876496, -0.21946734, -0.00170092],
       [-0.47759756, -0.18496966,  0.06038696],
       [ 0.42129501,  0.14404399, -0.04774545],
       [-0.55405987, -0.29139113, -0.00144982],
       [ 0.4852764 , -0.20393458,  0.00291617],
       [ 0.4949363 , -0.2903091 ,  0.09697553],
       [ 0.05712002,  0.07213162, -0.10360716],
       [ 0.50235017, -0.32336932,  0.0492053 ],
       [ 0.0825728 ,  0.41094416, -0.43303314],
       [ 0.02831325,  0.34195305, -0.48282765],
       [ 0.42629387, -0.34064432,  0.09369834],
       [-0.42986511, -0.34569822, -0.06866186],
       [-0.28498096,  0.37565277,  0.04872086],
       [ 0.53972532, -0.26296676, -0.11461176],
       [-0.10268123,  0.07004231, -0.09961283],
       [-0.12205622,  0.39680554, -0.38694523],
       [ 0.09516951,  0.34909237,  0.11425284],
       [-0.21338476, -0.01232546, -0.25703284],
       [ 0.54312394, -0.19287183, -0.16334848],
       [-0.41395087, -0.19145662,  0.2523077 ],
       [-0.25801208, -0.14932942,  0.1175691 ],
       [ 0.36932289, -0.29607148,  0.02186204],
       [ 0.50822896, -0.2870093 ,  0.05553935],
       [-0.2468829 ,  0.45405736,  0.1652378 ],
       [-0.4330343 , -0.34533259, -0.03178374],
       [ 0.49430774, -0.25175845, -0.01101601],
       [ 0.46089584, -0.14071424, -0.2512617 ],
       [-0.09086334,  0.47269742, -0.09373398],
       [-0.01108765,  0.44598271,  0.20790064],
       [ 0.52233259, -0.00388716,  0.03678259],
       [ 0.55459287, -0.25669238,  0.08960939],
       [ 0.21675862,  0.02881612, -0.18596552],
       [-0.48551267, -0.37207308,  0.05100079],
       [ 0.20306889,  0.27511653,  0.10026206],
       [ 0.4072456 , -0.02434534, -0.33738949],
       [ 0.11052553,  0.3994289 ,  0.2206256 ],
       [-0.42669954, -0.15222673,  0.03267924],
       [ 0.54565478, -0.26585069,  0.01385891],
       [-0.23686714,  0.32583902,  0.22455279],
       [-0.44797615, -0.11639254, -0.1433838 ],
       [-0.42847489, -0.13918469, -0.19172602],
       [ 0.45783443, -0.26421243,  0.18890158],
       [ 0.36439196,  0.15349983, -0.42755586],
       [-0.35966917, -0.10060235, -0.18437517],
       [ 0.50774935, -0.32236734,  0.13423155],
       [-0.42986088, -0.03974751,  0.2554042 ],
       [-0.08206355,  0.55737804,  0.24948142],
       [ 0.4348156 , -0.09459121,  0.0750198 ],
       [ 0.46000597, -0.12642596,  0.26511751],
       [-0.06848109,  0.53100398,  0.27178703],
       [ 0.54264617, -0.30364928, -0.02435033],
       [-0.48454134, -0.36188108, -0.10963371],
       [-0.16373689,  0.24489533,  0.49631273],
       [-0.42700832, -0.21441888,  0.21996779],
       [ 0.44527141, -0.01143512, -0.06351893],
       [-0.45586264, -0.1222922 ,  0.17539418],
       [-0.31868506, -0.25861763, -0.0075568 ],
       [-0.56664551, -0.33740412,  0.01938689],
       [ 0.54022304, -0.09810893, -0.23829404],
       [ 0.08730946,  0.26251591,  0.1276179 ],
       [-0.06833319,  0.50092727,  0.23784857],
       [ 0.05223849,  0.30044537,  0.35549542],
       [-0.02479152,  0.30492053,  0.14320701],
       [-0.5742329 , -0.36787436, -0.05923698],
       [-0.43158861, -0.35676266,  0.17918183],
       [-0.10053232,  0.34872481, -0.08298016],
       [-0.25488205,  0.29234717, -0.13530663],
       [ 0.084828  , -0.01548933,  0.41557076],
       [ 0.24843376,  0.44071442, -0.22403548],
       [-0.51509754, -0.31690723, -0.16872094],
       [-0.32826448, -0.27954989,  0.14231306],
       [ 0.30235077, -0.20219555,  0.08139271],
       [ 0.54588834, -0.33399627,  0.04688055],
       [-0.49096651, -0.08762216,  0.12999356],
       [-0.18211114,  0.50295302,  0.21844014],
       [-0.27321724,  0.18013773, -0.23297374],
       [-0.07477023,  0.43362447,  0.36287709],
       [ 0.36143257, -0.07787757,  0.12685681],
       [ 0.26652235,  0.05382953,  0.19997219],
       [ 0.5870593 , -0.22857012, -0.1450103 ],
       [-0.10054304,  0.55813867, -0.23307095],
       [ 0.02558386,  0.4908861 , -0.31394702],
       [-0.03481995,  0.54956587,  0.02738717],
       [ 0.55004401, -0.20326382, -0.15106777],
       [-0.44633866, -0.35935537, -0.06283923]])

In [118]:
X_test

array([[ 0.51724855, -0.20733354, -0.15204225],
       [-0.35659728, -0.27078428, -0.07742099],
       [ 0.20209022,  0.27919933, -0.05515451],
       [ 0.50770965, -0.23743092,  0.1119616 ],
       [-0.05267404,  0.09711069,  0.12594753],
       [-0.00583105, -0.00181217,  0.2022857 ],
       [ 0.45110323, -0.25282825,  0.06411794],
       [-0.52560966, -0.23951089,  0.01057443],
       [-0.05837639,  0.58252972, -0.17360527],
       [-0.21136379,  0.45077089,  0.00545542],
       [-0.42541139, -0.09682475, -0.19438978],
       [-0.38888458, -0.21989719, -0.05861082],
       [ 0.55194514, -0.38360327,  0.03575161],
       [ 0.26426831,  0.19226804, -0.06668801],
       [-0.41103551, -0.3073718 ,  0.09629044],
       [ 0.03951446,  0.54224351, -0.18432215],
       [ 0.28687297, -0.18774567,  0.20273863],
       [ 0.40787393, -0.32590565,  0.06436832],
       [-0.27112857,  0.11597436, -0.28751112],
       [ 0.55031685, -0.21741004, -0.00277081],
       [ 0.17146409,  0.16428611, -0.24673489],
       [ 0.37431291,  0.03232886, -0.06898501],
       [ 0.2404924 , -0.03340247,  0.41018382],
       [ 0.07421656,  0.55798051, -0.22891316],
       [-0.16070184,  0.1376764 , -0.08885201],
       [-0.03696783,  0.5258847 , -0.06166811],
       [ 0.01036581,  0.40004834,  0.14312976],
       [-0.12447074,  0.52140773,  0.10256603],
       [-0.15046312,  0.15866417,  0.3152446 ],
       [-0.5114672 , -0.33036781, -0.12370082],
       [ 0.48944836, -0.1392094 , -0.00066134],
       [ 0.56104669, -0.29829666, -0.01397277],
       [-0.27399735,  0.24155212,  0.17994176],
       [ 0.29744506, -0.21436575,  0.05249225],
       [ 0.48800317, -0.22597598, -0.1989829 ],
       [ 0.47111241,  0.00547682, -0.14718292],
       [-0.44929736, -0.22606139,  0.01215024],
       [-0.29140136,  0.29663   ,  0.01802688],
       [ 0.09680089,  0.41696793, -0.05218748],
       [-0.55634178, -0.37329747,  0.03291142],
       [ 0.41586756,  0.11044567,  0.12944564],
       [ 0.43993916, -0.21018463,  0.20956306],
       [ 0.08852529,  0.50300287, -0.02294702],
       [-0.08434537,  0.4778219 , -0.42150398],
       [-0.0718963 ,  0.51462328,  0.18405413]])

In [120]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [122]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [88]:
result
#6

           Logistic SVMl SVMNl  KNN Navie  Decision Random
Kernal_PCA      1.0  1.0   1.0  1.0   1.0  0.977778    1.0

In [100]:
result
#5

           Logistic SVMl SVMNl  KNN Navie  Decision Random
Kernal_PCA      1.0  1.0   1.0  1.0   1.0  0.955556    1.0

In [112]:
result
#4

           Logistic SVMl SVMNl  KNN Navie  Decision Random
Kernal_PCA      1.0  1.0   1.0  1.0   1.0  0.977778    1.0

In [124]:
result
#3

           Logistic SVMl SVMNl       KNN Navie  Decision    Random
Kernal_PCA      1.0  1.0   1.0  0.955556   1.0  0.955556  0.977778