In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [127]:
def KernlPCA(train_x,test_x,n):
    print("Train_X", train_x)
    from sklearn.decomposition import KernelPCA
    kpca = KernelPCA(n_components = n, kernel = 'rbf')
    train_x = kpca.fit_transform(train_x)
    test_x = kpca.transform(test_x)

    return train_x, test_x #lda_features

In [91]:
def split_scalar(indep_X,dep_Y):
        train_x, x_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        train_x = sc.fit_transform(train_x)
        test_x = sc.transform(x_test)    
        return train_x, test_x, y_train, y_test

In [93]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return classifier,Accuracy,report,X_test,y_test,cm

In [95]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return classifier,Accuracy,report,X_test,y_test,cm

In [97]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [99]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [100]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [103]:

def knn(X_train,y_train,X_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [105]:
def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion  = 'entropy',random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [107]:
def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [109]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['Kernal_PCA'],columns=['Logistic','SVMl','SVMNl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        # df.loc[row_indexer, "col"] = values
        dataframe.loc[idex,'Logistic']=acclog[number]
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMNl']=accsvmnl[number]
        dataframe.loc[idex,'KNN']=accknn[number]
        dataframe.loc[idex,'Navie']=accnav[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
        # print(dataframe)
        # dataframe['Logistic'][idex]=acclog[number]       
       # dataframe['SVMl'][idex]=accsvml[number]
        # dataframe['SVMnl'][idex]=accsvmnl[number]
        # dataframe['KNN'][idex]=accknn[number]
        # dataframe['Navie'][idex]=accnav[number]
        # dataframe['Decision'][idex]=accdes[number]
        # dataframe['Random'][idex]=accrf[number]
    return dataframe

In [111]:

# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
df2=dataset.copy()
df2

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [113]:

df2 = pd.get_dummies(df2, drop_first=True)
df2

      User ID   Age  EstimatedSalary  Purchased  Gender_Male
0    15624510  19.0          19000.0          0         True
1    15810944  35.0          20000.0          0         True
2    15668575  26.0          43000.0          0        False
3    15603246  27.0          57000.0          0        False
4    15804002  19.0          76000.0          0         True
..        ...   ...              ...        ...          ...
395  15691863  46.0          41000.0          1        False
396  15706071  51.0          23000.0          1         True
397  15654296  50.0          20000.0          1        False
398  15755018  36.0          33000.0          0         True
399  15594041  49.0          36000.0          1        False

[400 rows x 5 columns]

In [115]:
X = df2.iloc[:, [2, 3]].values
Y = df2.iloc[:, 4].values

In [117]:
X

array([[1.90e+04, 0.00e+00],
       [2.00e+04, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [5.70e+04, 0.00e+00],
       [7.60e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [8.40e+04, 0.00e+00],
       [1.50e+05, 1.00e+00],
       [3.30e+04, 0.00e+00],
       [6.50e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [5.20e+04, 0.00e+00],
       [8.60e+04, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [2.50e+04, 1.00e+00],
       [2.60e+04, 1.00e+00],
       [2.80e+04, 1.00e+00],
       [2.90e+04, 1.00e+00],
       [2.20e+04, 1.00e+00],
       [4.90e+04, 1.00e+00],
       [4.10e+04, 1.00e+00],
       [2.20e+04, 1.00e+00],
       [2.30e+04, 1.00e+00],
       [2.00e+04, 1.00e+00],
       [2.80e+04, 1.00e+00],
       [3.00e+04, 1.00e+00],
       [4.30e+04, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [7.40e+04, 0.00e+00],
       [1.37e+05, 1.00e+00],
       [1.60e+04, 0.00e+00],
       [4.40e+04, 0.00e+00],
       [9.00e+04, 0.00e+00],
       [2.70e+04, 0.00e+00],
       [2.80e+04, 0.00e+00],
       [4.90e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [3.10e+04, 0.00e+00],
       [1.70e+04, 0.00e+00],
       [5.10e+04, 0.00e+00],
       [1.08e+05, 0.00e+00],
       [1.50e+04, 0.00e+00],
       [8.40e+04, 0.00e+00],
       [2.00e+04, 0.00e+00],
       [7.90e+04, 0.00e+00],
       [5.40e+04, 0.00e+00],
       [1.35e+05, 1.00e+00],
       [8.90e+04, 0.00e+00],
       [3.20e+04, 0.00e+00],
       [4.40e+04, 0.00e+00],
       [8.30e+04, 0.00e+00],
       [2.30e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [5.50e+04, 0.00e+00],
       [4.80e+04, 0.00e+00],
       [7.90e+04, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [1.17e+05, 0.00e+00],
       [2.00e+04, 0.00e+00],
       [8.70e+04, 0.00e+00],
       [6.60e+04, 0.00e+00],
       [1.20e+05, 1.00e+00],
       [8.30e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [1.90e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [6.30e+04, 0.00e+00],
       [6.80e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [2.70e+04, 0.00e+00],
       [2.30e+04, 0.00e+00],
       [1.13e+05, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [1.12e+05, 1.00e+00],
       [5.20e+04, 0.00e+00],
       [2.70e+04, 0.00e+00],
       [8.70e+04, 0.00e+00],
       [1.70e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [4.20e+04, 0.00e+00],
       [4.90e+04, 0.00e+00],
       [8.80e+04, 0.00e+00],
       [6.20e+04, 0.00e+00],
       [1.18e+05, 1.00e+00],
       [5.50e+04, 0.00e+00],
       [8.50e+04, 0.00e+00],
       [8.10e+04, 0.00e+00],
       [5.00e+04, 0.00e+00],
       [8.10e+04, 0.00e+00],
       [1.16e+05, 0.00e+00],
       [1.50e+04, 0.00e+00],
       [2.80e+04, 0.00e+00],
       [8.30e+04, 0.00e+00],
       [4.40e+04, 0.00e+00],
       [2.50e+04, 0.00e+00],
       [1.23e+05, 1.00e+00],
       [7.30e+04, 0.00e+00],
       [3.70e+04, 0.00e+00],
       [8.80e+04, 0.00e+00],
       [5.90e+04, 0.00e+00],
       [8.60e+04, 0.00e+00],
       [1.49e+05, 1.00e+00],
       [2.10e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [3.50e+04, 0.00e+00],
       [8.90e+04, 0.00e+00],
       [8.60e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [7.10e+04, 0.00e+00],
       [7.10e+04, 0.00e+00],
       [6.10e+04, 0.00e+00],
       [5.50e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [5.70e+04, 0.00e+00],
       [7.50e+04, 0.00e+00],
       [5.20e+04, 0.00e+00],
       [5.90e+04, 0.00e+00],
       [5.90e+04, 0.00e+00],
       [7.50e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [7.50e+04, 0.00e+00],
       [5.30e+04, 0.00e+00],
       [5.10e+04, 0.00e+00],
       [6.10e+04, 0.00e+00],
       [6.50e+04, 0.00e+00],
       [3.20e+04, 0.00e+00],
       [1.70e+04, 0.00e+00],
       [8.40e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [3.10e+04, 0.00e+00],
       [8.70e+04, 0.00e+00],
       [6.80e+04, 0.00e+00],
       [5.50e+04, 0.00e+00],
       [6.30e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [1.07e+05, 1.00e+00],
       [5.90e+04, 0.00e+00],
       [2.50e+04, 0.00e+00],
       [8.50e+04, 0.00e+00],
       [6.80e+04, 0.00e+00],
       [5.90e+04, 0.00e+00],
       [8.90e+04, 0.00e+00],
       [2.50e+04, 0.00e+00],
       [8.90e+04, 0.00e+00],
       [9.60e+04, 1.00e+00],
       [3.00e+04, 0.00e+00],
       [6.10e+04, 0.00e+00],
       [7.40e+04, 0.00e+00],
       [1.50e+04, 0.00e+00],
       [4.50e+04, 0.00e+00],
       [7.60e+04, 0.00e+00],
       [5.00e+04, 0.00e+00],
       [4.70e+04, 0.00e+00],
       [1.50e+04, 0.00e+00],
       [5.90e+04, 0.00e+00],
       [7.50e+04, 0.00e+00],
       [3.00e+04, 0.00e+00],
       [1.35e+05, 1.00e+00],
       [1.00e+05, 1.00e+00],
       [9.00e+04, 0.00e+00],
       [3.30e+04, 0.00e+00],
       [3.80e+04, 0.00e+00],
       [6.90e+04, 0.00e+00],
       [8.60e+04, 0.00e+00],
       [5.50e+04, 0.00e+00],
       [7.10e+04, 0.00e+00],
       [1.48e+05, 1.00e+00],
       [4.70e+04, 0.00e+00],
       [8.80e+04, 0.00e+00],
       [1.15e+05, 0.00e+00],
       [1.18e+05, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [2.80e+04, 0.00e+00],
       [4.70e+04, 0.00e+00],
       [2.20e+04, 0.00e+00],
       [2.30e+04, 0.00e+00],
       [3.40e+04, 0.00e+00],
       [1.60e+04, 0.00e+00],
       [7.10e+04, 0.00e+00],
       [1.17e+05, 1.00e+00],
       [4.30e+04, 0.00e+00],
       [6.00e+04, 0.00e+00],
       [6.60e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [4.10e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [3.20e+04, 0.00e+00],
       [8.40e+04, 0.00e+00],
       [2.60e+04, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [7.00e+04, 0.00e+00],
       [8.90e+04, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [7.90e+04, 0.00e+00],
       [3.60e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [2.20e+04, 0.00e+00],
       [3.90e+04, 0.00e+00],
       [7.40e+04, 0.00e+00],
       [1.34e+05, 1.00e+00],
       [7.10e+04, 0.00e+00],
       [1.01e+05, 1.00e+00],
       [4.70e+04, 0.00e+00],
       [1.30e+05, 1.00e+00],
       [1.14e+05, 0.00e+00],
       [1.42e+05, 1.00e+00],
       [2.20e+04, 0.00e+00],
       [9.60e+04, 1.00e+00],
       [1.50e+05, 1.00e+00],
       [4.20e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [1.08e+05, 1.00e+00],
       [6.50e+04, 0.00e+00],
       [7.80e+04, 0.00e+00],
       [9.60e+04, 0.00e+00],
       [1.43e+05, 1.00e+00],
       [8.00e+04, 0.00e+00],
       [9.10e+04, 1.00e+00],
       [1.44e+05, 1.00e+00],
       [1.02e+05, 1.00e+00],
       [6.00e+04, 0.00e+00],
       [5.30e+04, 0.00e+00],
       [1.26e+05, 1.00e+00],
       [1.33e+05, 1.00e+00],
       [7.20e+04, 0.00e+00],
       [8.00e+04, 1.00e+00],
       [1.47e+05, 1.00e+00],
       [4.20e+04, 0.00e+00],
       [1.07e+05, 1.00e+00],
       [8.60e+04, 1.00e+00],
       [1.12e+05, 0.00e+00],
       [7.90e+04, 1.00e+00],
       [5.70e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [1.43e+05, 1.00e+00],
       [1.49e+05, 1.00e+00],
       [5.90e+04, 0.00e+00],
       [8.80e+04, 1.00e+00],
       [1.04e+05, 1.00e+00],
       [7.20e+04, 0.00e+00],
       [1.46e+05, 1.00e+00],
       [5.00e+04, 0.00e+00],
       [1.22e+05, 1.00e+00],
       [5.20e+04, 0.00e+00],
       [9.70e+04, 1.00e+00],
       [3.90e+04, 0.00e+00],
       [5.20e+04, 0.00e+00],
       [1.34e+05, 1.00e+00],
       [1.46e+05, 1.00e+00],
       [4.40e+04, 0.00e+00],
       [9.00e+04, 1.00e+00],
       [7.20e+04, 0.00e+00],
       [5.70e+04, 0.00e+00],
       [9.50e+04, 1.00e+00],
       [1.31e+05, 1.00e+00],
       [7.70e+04, 0.00e+00],
       [1.44e+05, 1.00e+00],
       [1.25e+05, 1.00e+00],
       [7.20e+04, 0.00e+00],
       [9.00e+04, 1.00e+00],
       [1.08e+05, 1.00e+00],
       [7.50e+04, 0.00e+00],
       [7.40e+04, 0.00e+00],
       [1.44e+05, 1.00e+00],
       [6.10e+04, 0.00e+00],
       [1.33e+05, 0.00e+00],
       [7.60e+04, 1.00e+00],
       [4.20e+04, 1.00e+00],
       [1.06e+05, 1.00e+00],
       [2.60e+04, 1.00e+00],
       [7.40e+04, 1.00e+00],
       [7.10e+04, 0.00e+00],
       [8.80e+04, 1.00e+00],
       [3.80e+04, 1.00e+00],
       [3.60e+04, 1.00e+00],
       [8.80e+04, 1.00e+00],
       [6.10e+04, 0.00e+00],
       [7.00e+04, 1.00e+00],
       [2.10e+04, 1.00e+00],
       [1.41e+05, 0.00e+00],
       [9.30e+04, 1.00e+00],
       [6.20e+04, 0.00e+00],
       [1.38e+05, 1.00e+00],
       [7.90e+04, 0.00e+00],
       [7.80e+04, 1.00e+00],
       [1.34e+05, 1.00e+00],
       [8.90e+04, 1.00e+00],
       [3.90e+04, 1.00e+00],
       [7.70e+04, 0.00e+00],
       [5.70e+04, 0.00e+00],
       [6.30e+04, 0.00e+00],
       [7.30e+04, 1.00e+00],
       [1.12e+05, 1.00e+00],
       [7.90e+04, 0.00e+00],
       [1.17e+05, 1.00e+00],
       [3.80e+04, 1.00e+00],
       [7.40e+04, 1.00e+00],
       [1.37e+05, 1.00e+00],
       [7.90e+04, 1.00e+00],
       [6.00e+04, 0.00e+00],
       [5.40e+04, 0.00e+00],
       [1.34e+05, 0.00e+00],
       [1.13e+05, 1.00e+00],
       [1.25e+05, 1.00e+00],
       [5.00e+04, 0.00e+00],
       [7.00e+04, 0.00e+00],
       [9.60e+04, 1.00e+00],
       [5.00e+04, 0.00e+00],
       [1.41e+05, 1.00e+00],
       [7.90e+04, 0.00e+00],
       [7.50e+04, 1.00e+00],
       [1.04e+05, 1.00e+00],
       [5.50e+04, 0.00e+00],
       [3.20e+04, 1.00e+00],
       [6.00e+04, 0.00e+00],
       [1.38e+05, 1.00e+00],
       [8.20e+04, 1.00e+00],
       [5.20e+04, 0.00e+00],
       [3.00e+04, 1.00e+00],
       [1.31e+05, 1.00e+00],
       [6.00e+04, 0.00e+00],
       [7.20e+04, 0.00e+00],
       [7.50e+04, 0.00e+00],
       [1.18e+05, 1.00e+00],
       [1.07e+05, 1.00e+00],
       [5.10e+04, 0.00e+00],
       [1.19e+05, 1.00e+00],
       [6.50e+04, 0.00e+00],
       [6.50e+04, 0.00e+00],
       [6.00e+04, 1.00e+00],
       [5.40e+04, 0.00e+00],
       [1.44e+05, 1.00e+00],
       [7.90e+04, 0.00e+00],
       [5.50e+04, 0.00e+00],
       [1.22e+05, 1.00e+00],
       [1.04e+05, 1.00e+00],
       [7.50e+04, 0.00e+00],
       [6.50e+04, 0.00e+00],
       [5.10e+04, 1.00e+00],
       [1.05e+05, 1.00e+00],
       [6.30e+04, 0.00e+00],
       [7.20e+04, 1.00e+00],
       [1.08e+05, 1.00e+00],
       [7.70e+04, 0.00e+00],
       [6.10e+04, 0.00e+00],
       [1.13e+05, 1.00e+00],
       [7.50e+04, 0.00e+00],
       [9.00e+04, 1.00e+00],
       [5.70e+04, 0.00e+00],
       [9.90e+04, 1.00e+00],
       [3.40e+04, 1.00e+00],
       [7.00e+04, 1.00e+00],
       [7.20e+04, 0.00e+00],
       [7.10e+04, 1.00e+00],
       [5.40e+04, 0.00e+00],
       [1.29e+05, 1.00e+00],
       [3.40e+04, 1.00e+00],
       [5.00e+04, 1.00e+00],
       [7.90e+04, 0.00e+00],
       [1.04e+05, 1.00e+00],
       [2.90e+04, 1.00e+00],
       [4.70e+04, 1.00e+00],
       [8.80e+04, 1.00e+00],
       [7.10e+04, 0.00e+00],
       [2.60e+04, 1.00e+00],
       [4.60e+04, 1.00e+00],
       [8.30e+04, 1.00e+00],
       [7.30e+04, 0.00e+00],
       [1.30e+05, 1.00e+00],
       [8.00e+04, 0.00e+00],
       [3.20e+04, 1.00e+00],
       [7.40e+04, 0.00e+00],
       [5.30e+04, 0.00e+00],
       [8.70e+04, 1.00e+00],
       [2.30e+04, 1.00e+00],
       [6.40e+04, 0.00e+00],
       [3.30e+04, 1.00e+00],
       [1.39e+05, 1.00e+00],
       [2.80e+04, 1.00e+00],
       [3.30e+04, 1.00e+00],
       [6.00e+04, 1.00e+00],
       [3.90e+04, 1.00e+00],
       [7.10e+04, 0.00e+00],
       [3.40e+04, 1.00e+00],
       [3.50e+04, 1.00e+00],
       [3.30e+04, 1.00e+00],
       [2.30e+04, 1.00e+00],
       [4.50e+04, 1.00e+00],
       [4.20e+04, 1.00e+00],
       [5.90e+04, 0.00e+00],
       [4.10e+04, 1.00e+00],
       [2.30e+04, 1.00e+00],
       [2.00e+04, 1.00e+00],
       [3.30e+04, 0.00e+00],
       [3.60e+04, 1.00e+00]])

In [119]:
train_x, test_x, y_train, y_test=split_scalar(X,Y)

In [129]:
X_train, X_test=KernlPCA(train_x,test_x,4)       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

Train_X [[-0.88670699 -0.76635604]
 [ 1.46173768  1.30487651]
 [-0.5677824  -0.76635604]
 [ 1.89663484  1.30487651]
 [-1.40858358  1.30487651]
 [ 0.99784738  1.30487651]
 [-0.79972756 -0.76635604]
 [-0.24885782 -0.76635604]
 [-0.5677824  -0.76635604]
 [-0.19087153 -0.76635604]
 [-1.29261101 -0.76635604]
 [-0.5677824  -0.76635604]
 [ 0.09905991  1.30487651]
 [-0.59677555  1.30487651]
 [-1.17663843  1.30487651]
 [-0.13288524 -0.76635604]
 [ 1.78066227  1.30487651]
 [ 0.56295021 -0.76635604]
 [ 0.35999821 -0.76635604]
 [-0.53878926  1.30487651]
 [-1.58254245 -0.76635604]
 [ 0.93986109  1.30487651]
 [ 1.22979253 -0.76635604]
 [ 1.08482681  1.30487651]
 [-0.48080297 -0.76635604]
 [-0.30684411 -0.76635604]
 [-0.8287207   1.30487651]
 [ 1.8676417   1.30487651]
 [ 1.25878567  1.30487651]
 [ 2.27354572  1.30487651]
 [-1.58254245 -0.76635604]
 [-0.79972756  1.30487651]
 [-1.46656987 -0.76635604]
 [ 2.30253886  1.30487651]
 [ 0.76590222 -0.76635604]
 [-0.30684411 -0.76635604]
 [ 0.76590222  1.30487651]
 [ 0.56295021 -0.76635604]
 [ 0.07006676 -0.76635604]
 [-1.26361786  1.30487651]
 [-0.01691267 -0.76635604]
 [ 0.35999821 -0.76635604]
 [ 0.12805305 -0.76635604]
 [ 0.30201192 -0.76635604]
 [ 0.07006676 -0.76635604]
 [ 2.30253886  1.30487651]
 [ 0.04107362  1.30487651]
 [ 2.21555943  1.30487651]
 [ 0.27301877  1.30487651]
 [ 0.1570462  -0.76635604]
 [-0.53878926 -0.76635604]
 [ 0.1570462  -0.76635604]
 [ 0.24402563  1.30487651]
 [-0.24885782 -0.76635604]
 [ 1.11381995  1.30487651]
 [ 0.35999821 -0.76635604]
 [ 0.12805305  1.30487651]
 [-0.13288524 -0.76635604]
 [ 0.30201192 -0.76635604]
 [ 1.37475825  1.30487651]
 [-0.24885782 -0.76635604]
 [-0.04590581 -0.76635604]
 [-0.74174127 -0.76635604]
 [ 0.50496393  1.30487651]
 [-1.06066585 -0.76635604]
 [ 0.59194336 -0.76635604]
 [-0.79972756 -0.76635604]
 [ 1.54871711  1.30487651]
 [ 1.40375139  1.30487651]
 [ 0.50496393 -0.76635604]
 [ 0.04107362 -0.76635604]
 [ 0.01208048  1.30487651]
 [-0.88670699 -0.76635604]
 [-1.3505973   1.30487651]
 [ 2.24455257  1.30487651]
 [ 1.98361427  1.30487651]
 [ 0.47597078 -0.76635604]
 [ 0.27301877 -0.76635604]
 [ 1.98361427  1.30487651]
 [-1.3505973   1.30487651]
 [-0.27785096 -0.76635604]
 [ 1.25878567 -0.76635604]
 [ 1.08482681  1.30487651]
 [-1.06066585  1.30487651]
 [ 0.30201192 -0.76635604]
 [ 0.76590222  1.30487651]
 [-1.49556302 -0.76635604]
 [ 0.04107362 -0.76635604]
 [ 1.72267598  1.30487651]
 [ 0.18603934  1.30487651]
 [-0.74174127 -0.76635604]
 [ 1.40375139  1.30487651]
 [ 0.59194336  1.30487651]
 [-1.14764529  1.30487651]
 [-0.77073441 -0.76635604]
 [ 0.24402563 -0.76635604]
 [-0.30684411 -0.76635604]
 [-0.79972756 -0.76635604]
 [ 0.12805305 -0.76635604]
 [ 0.6209365   1.30487651]
 [-0.30684411 -0.76635604]
 [-0.3648304  -0.76635604]
 [ 2.12857999  1.30487651]
 [-1.26361786  1.30487651]
 [-0.91570013  1.30487651]
 [ 1.25878567  1.30487651]
 [ 2.12857999  1.30487651]
 [-1.23462472 -0.76635604]
 [ 0.91086794  1.30487651]
 [-0.71274813  1.30487651]
 [ 0.35999821 -0.76635604]
 [-1.3505973   1.30487651]
 [-0.13288524 -0.76635604]
 [ 0.41798449 -0.76635604]
 [-0.30684411 -0.76635604]
 [ 0.41798449 -0.76635604]
 [-1.20563157 -0.76635604]
 [ 0.04107362 -0.76635604]
 [-0.42281668 -0.76635604]
 [-1.00267957  1.30487651]
 [-1.20563157  1.30487651]
 [-0.13288524 -0.76635604]
 [-1.52455616 -0.76635604]
 [-1.20563157  1.30487651]
 [ 2.07059371 -0.76635604]
 [-1.52455616 -0.76635604]
 [ 0.79489537  1.30487651]
 [-0.30684411 -0.76635604]
 [-1.23462472 -0.76635604]
 [-1.49556302 -0.76635604]
 [ 0.53395707  1.30487651]
 [-0.33583725 -0.76635604]
 [-0.27785096  1.30487651]
 [-1.03167271  1.30487651]
 [ 0.07006676 -0.76635604]
 [ 0.8818748   1.30487651]
 [-1.40858358 -0.76635604]
 [ 0.59194336 -0.76635604]
 [ 0.53395707 -0.76635604]
 [-1.089659   -0.76635604]
 [-1.43757673  1.30487651]
 [-0.30684411 -0.76635604]
 [-0.74174127 -0.76635604]
 [ 0.07006676 -0.76635604]
 [ 2.09958685  1.30487651]
 [-1.089659    1.30487651]
 [ 0.04107362 -0.76635604]
 [ 0.12805305 -0.76635604]
 [ 0.1570462  -0.76635604]
 [ 0.18603934 -0.76635604]
 [-1.29261101  1.30487651]
 [-0.24885782 -0.76635604]
 [ 1.22979253  1.30487651]
 [ 0.30201192 -0.76635604]
 [ 0.1570462  -0.76635604]
 [-0.65476184 -0.76635604]
 [ 0.1570462   1.30487651]
 [-1.29261101 -0.76635604]
 [ 0.30201192 -0.76635604]
 [-0.27785096 -0.76635604]
 [-0.50979612 -0.76635604]
 [ 1.6067034   1.30487651]
 [-1.17663843  1.30487651]
 [ 1.63569655  1.30487651]
 [ 1.8676417  -0.76635604]
 [-0.3648304  -0.76635604]
 [ 0.04107362 -0.76635604]
 [-0.24885782 -0.76635604]
 [-1.23462472 -0.76635604]
 [-0.27785096 -0.76635604]
 [ 0.12805305  1.30487651]
 [-1.3505973   1.30487651]
 [ 0.07006676  1.30487651]
 [ 1.37475825  1.30487651]
 [ 0.01208048  1.30487651]
 [ 0.30201192 -0.76635604]
 [ 0.73690908  1.30487651]
 [-0.50979612 -0.76635604]
 [ 0.27301877 -0.76635604]
 [-0.42281668 -0.76635604]
 [ 0.1570462  -0.76635604]
 [-1.20563157 -0.76635604]
 [ 2.01260742  1.30487651]
 [-1.49556302 -0.76635604]
 [-0.53878926 -0.76635604]
 [ 1.83864855 -0.76635604]
 [-1.089659   -0.76635604]
 [-1.37959044 -0.76635604]
 [-0.42281668 -0.76635604]
 [ 0.99784738  1.30487651]
 [ 1.43274454  1.30487651]
 [-0.48080297 -0.76635604]
 [ 2.15757314  1.30487651]
 [-0.1038921  -0.76635604]
 [ 1.95462113  1.30487651]
 [-0.33583725 -0.76635604]
 [-0.8287207  -0.76635604]
 [-1.37959044  1.30487651]
 [-1.58254245 -0.76635604]
 [-1.46656987 -0.76635604]
 [ 0.12805305 -0.76635604]
 [ 1.51972397  1.30487651]
 [ 0.09905991 -0.76635604]
 [ 0.04107362 -0.76635604]
 [-1.3505973  -0.76635604]
 [ 0.07006676 -0.76635604]
 [ 0.38899135 -0.76635604]
 [-1.26361786  1.30487651]
 [-0.74174127 -0.76635604]
 [ 0.1570462  -0.76635604]
 [-0.65476184 -0.76635604]
 [-0.04590581 -0.76635604]
 [-0.45180983 -0.76635604]
 [ 1.89663484  1.30487651]
 [ 1.28777882 -0.76635604]
 [-0.97368642  1.30487651]
 [ 1.83864855  1.30487651]
 [-0.24885782 -0.76635604]
 [ 0.56295021 -0.76635604]
 [-1.5535493  -0.76635604]
 [-1.11865214 -0.76635604]
 [ 0.07006676 -0.76635604]
 [-1.06066585 -0.76635604]
 [ 1.6067034   1.30487651]
 [ 1.78066227  1.30487651]
 [ 0.04107362 -0.76635604]
 [-0.21986468 -0.76635604]
 [ 0.07006676 -0.76635604]
 [-0.19087153 -0.76635604]
 [-0.65476184  1.30487651]
 [ 1.3457651  -0.76635604]
 [-0.59677555 -0.76635604]
 [ 0.12805305 -0.76635604]
 [-0.30684411 -0.76635604]
 [ 0.56295021  1.30487651]
 [ 0.27301877 -0.76635604]
 [ 0.35999821  1.30487651]
 [-0.3648304  -0.76635604]
 [-1.03167271  1.30487651]
 [ 1.11381995 -0.76635604]
 [ 0.07006676 -0.76635604]
 [ 0.04107362 -0.76635604]
 [ 1.05583366  1.30487651]
 [-0.3648304  -0.76635604]
 [ 0.07006676 -0.76635604]
 [-1.3505973  -0.76635604]
 [ 1.11381995  1.30487651]
 [-1.52455616 -0.76635604]
 [ 1.8676417   1.30487651]
 [-0.77073441 -0.76635604]
 [-0.77073441 -0.76635604]
 [-0.91570013 -0.76635604]
 [-0.71274813 -0.76635604]
 [ 0.07006676 -0.76635604]
 [ 1.8676417   1.30487651]
 [ 1.95462113  1.30487651]
 [-1.5535493  -0.76635604]
 [-1.089659   -0.76635604]
 [-0.1038921  -0.76635604]
 [ 0.09905991 -0.76635604]
 [ 0.27301877 -0.76635604]
 [-0.5677824   1.30487651]
 [-1.14764529 -0.76635604]
 [ 0.67892279  1.30487651]
 [-0.68375498  1.30487651]
 [-1.37959044 -0.76635604]
 [-0.94469328 -0.76635604]
 [-0.42281668 -0.76635604]
 [-0.45180983 -0.76635604]
 [-0.97368642 -0.76635604]
 [ 0.99784738  1.30487651]
 [-0.3648304  -0.76635604]
 [ 1.11381995  1.30487651]
 [-1.3505973  -0.76635604]
 [-0.13288524 -0.76635604]
 [-1.43757673  1.30487651]
 [ 0.47597078 -0.76635604]
 [ 0.27301877 -0.76635604]
 [-1.06066585  1.30487651]
 [ 0.07006676 -0.76635604]
 [-0.88670699  1.30487651]
 [-1.11865214 -0.76635604]
 [ 0.01208048 -0.76635604]
 [ 0.27301877 -0.76635604]
 [ 0.33100506 -0.76635604]
 [ 0.30201192 -0.76635604]
 [ 0.44697764 -0.76635604]
 [-0.88670699  1.30487651]
 [ 0.53395707  1.30487651]
 [ 0.53395707  1.30487651]
 [ 2.331532    1.30487651]
 [-0.13288524 -0.76635604]
 [-0.45180983 -0.76635604]
 [-0.77073441 -0.76635604]
 [-0.50979612 -0.76635604]
 [-1.14764529  1.30487651]
 [-0.77073441 -0.76635604]
 [-0.50979612 -0.76635604]
 [-0.45180983 -0.76635604]
 [ 1.40375139 -0.76635604]]

In [131]:
X_train

array([[-0.39041115,  0.36445519, -0.35037262,  0.05368696],
       [ 0.77830581, -0.3816688 , -0.36108476, -0.03358735],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       ...,
       [-0.48509309,  0.11777864, -0.14702015,  0.07741766],
       [-0.49304559,  0.0759756 , -0.11189001,  0.07667906],
       [ 0.06097905, -0.35997039,  0.25630816, -0.32000923]])

In [133]:
X_test

array([[-0.32857955, -0.43935707,  0.32809491, -0.10065727],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       [-0.44812601, -0.31749158,  0.22366622, -0.006947  ],
       [-0.41428502, -0.36894177,  0.2678775 , -0.03595291],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       [-0.17584111,  0.55219018, -0.48951186, -0.03460519],
       [-0.11745754,  0.55897669, -0.48844397, -0.05940585],
       [ 0.66776283, -0.32951514, -0.40867215, -0.48534029],
       [-0.48918832, -0.20458725,  0.12672671,  0.03530416],
       [-0.42651628,  0.29550374, -0.29442919,  0.06574406],
       [-0.46951756,  0.17946925, -0.1985863 ,  0.07616147],
       [-0.49626124,  0.05498759, -0.09420149,  0.07582526],
       [-0.49626124,  0.05498759, -0.09420149,  0.07582526],
       [-0.4320697 , -0.34451019,  0.24688819, -0.02108004],
       [-0.34037119, -0.43298705,  0.32268959, -0.09226228],
       [ 0.05035728, -0.3680015 ,  0.26314205, -0.3157145 ],
       [-0.4320697 , -0.34451019,  0.24688819, -0.02108004],
       [-0.35189409, -0.42592127,  0.31667612, -0.08392609],
       [ 0.74792608, -0.38229192, -0.41212978, -0.26230261],
       [-0.19961328,  0.5445886 , -0.48567465, -0.02440667],
       [-0.45684445,  0.21947699, -0.23182304,  0.07381111],
       [ 0.66776283, -0.32951514, -0.40867215, -0.48534029],
       [-0.48037616,  0.13851585, -0.16439318,  0.07730947],
       [ 0.77581728, -0.30680331, -0.2046852 ,  0.32033448],
       [-0.27079574,  0.50428772, -0.45874454,  0.00601147],
       [ 0.68789297, -0.34504181, -0.41614846, -0.44994705],
       [-0.32857955, -0.43935707,  0.32809491, -0.10065727],
       [-0.40478401, -0.38015691,  0.27750551, -0.04363372],
       [-0.50389683, -0.08992047,  0.02870475,  0.06068492],
       [-0.34037119, -0.43298705,  0.32268959, -0.09226228],
       [-0.31653971, -0.44503471,  0.33289469, -0.10909656],
       [ 0.67653347,  0.01750021,  0.18806973,  0.56898308],
       [ 0.59268216,  0.32049445,  0.44000312,  0.33308524],
       [-0.48931971,  0.09691895, -0.12950771,  0.07720882],
       [-0.50276646, -0.0078542 , -0.04105691,  0.07130065],
       [-0.48509309,  0.11777864, -0.14702015,  0.07741766],
       [-0.39489976, -0.39069235,  0.28654342, -0.05145922],
       [-0.42651628,  0.29550374, -0.29442919,  0.06574406],
       [-0.33889275,  0.4379723 , -0.40863787,  0.03409081],
       [ 0.51235047,  0.57225158,  0.56725086, -0.14655523],
       [-0.31653971, -0.44503471,  0.33289469, -0.10909656],
       [-0.48509309,  0.11777864, -0.14702015,  0.07741766],
       [-0.36312801, -0.41815803,  0.31005341, -0.07566324],
       [-0.17584111,  0.55219018, -0.48951186, -0.03460519],
       [ 0.78392537, -0.3531741 , -0.28832087,  0.1617616 ],
       [-0.50276646, -0.0078542 , -0.04105691,  0.07130065],
       [-0.40478401, -0.38015691,  0.27750551, -0.04363372],
       [ 0.72688567, -0.14423174,  0.01570026,  0.54645203],
       [-0.29402976,  0.48500819, -0.44457644,  0.0157681 ],
       [ 0.70922263, -0.08858902,  0.07878354,  0.56988209],
       [ 0.77428629, -0.38478934, -0.3749631 , -0.0819443 ],
       [-0.23535207,  0.52773989, -0.47513026, -0.00907586],
       [-0.5011287 ,  0.01303377, -0.05875035,  0.07313714],
       [ 0.02836012, -0.38355808,  0.27646417, -0.30638305],
       [ 0.71819726, -0.1169436 ,  0.04720151,  0.56032704],
       [ 0.49987569,  0.58671601,  0.56304011, -0.21144921],
       [-0.37405312, -0.40969734,  0.30282201, -0.06748822],
       [-0.40478401, -0.38015691,  0.27750551, -0.04363372],
       [ 0.4871123 ,  0.59239858,  0.55196995, -0.26730724],
       [-0.17584111,  0.55219018, -0.48951186, -0.03460519],
       [-0.1522531 ,  0.5569543 , -0.49086748, -0.04468417],
       [ 0.53092506,  0.53420505,  0.55994374, -0.03517504],
       [-0.4403214 , -0.33131725,  0.23554957, -0.0139146 ],
       [ 0.76053548, -0.25151067, -0.12150271,  0.43394078],
       [-0.24722204,  0.52065635, -0.4703195 , -0.00400337],
       [ 0.69537489, -0.04428356,  0.12602035,  0.57601992],
       [-0.30427246, -0.45002495,  0.33709309, -0.11756569],
       [-0.50276646, -0.0078542 , -0.04105691,  0.07130065],
       [-0.45684445,  0.21947699, -0.23182304,  0.07381111],
       [-0.47998771, -0.2395054 ,  0.15667515,  0.02450526],
       [ 0.6242415 , -0.29352534, -0.38457591, -0.53437424],
       [-0.4320697 , -0.34451019,  0.24688819, -0.02108004],
       [-0.50281073, -0.10987972,  0.0457251 ,  0.05722456],
       [ 0.46716881,  0.58511006,  0.52373362, -0.33252755],
       [-0.30427246, -0.45002495,  0.33709309, -0.11756569],
       [-0.38465001, -0.40054093,  0.29498408, -0.05941544],
       [-0.41428502, -0.36894177,  0.2678775 , -0.03595291],
       [-0.50442286, -0.04925981, -0.00590609,  0.06664356],
       [ 0.50613905,  0.58058711,  0.56603023, -0.18006322],
       [ 0.77928531, -0.32208528, -0.23023865,  0.27728063],
       [ 0.66776283, -0.32951514, -0.40867215, -0.48534029],
       [-0.37405312, -0.40969734,  0.30282201, -0.06748822],
       [-0.49626124,  0.05498759, -0.09420149,  0.07582526],
       [-0.34966484,  0.42451921, -0.39812409,  0.03834703],
       [ 0.51853397,  0.56172059,  0.56666115, -0.11109877],
       [ 0.68126117,  0.00180979,  0.17270505,  0.57235203],
       [-0.44812601, -0.31749158,  0.22366622, -0.006947  ],
       [ 0.74792608, -0.38229192, -0.41212978, -0.26230261],
       [ 0.52781537,  0.54187554,  0.56232062, -0.05470974],
       [-0.50442286, -0.04925981, -0.00590609,  0.06664356],
       [-0.50117568, -0.1295443 ,  0.06251263,  0.05344886],
       [ 0.65367555, -0.31817335, -0.40191081, -0.50490216],
       [-0.46340104,  0.19960984, -0.21534032,  0.07513324],
       [-0.32792432,  0.45076245, -0.4185515 ,  0.02969172],
       [-0.36312801, -0.41815803,  0.31005341, -0.07566324],
       [ 0.75052232, -0.21880037, -0.07699245,  0.48001971],
       [-0.50281073, -0.10987972,  0.0457251 ,  0.05722456],
       [ 0.50301526,  0.58392739,  0.56475337, -0.19603118],
       [ 0.72688567, -0.14423174,  0.01570026,  0.54645203],
       [ 0.77376105, -0.29856186, -0.19146443,  0.34099708]])

In [135]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [137]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [88]:
result
#6

           Logistic SVMl SVMNl  KNN Navie  Decision Random
Kernal_PCA      1.0  1.0   1.0  1.0   1.0  0.977778    1.0

In [100]:
result
#5

           Logistic SVMl SVMNl  KNN Navie  Decision Random
Kernal_PCA      1.0  1.0   1.0  1.0   1.0  0.955556    1.0

In [77]:
result
#1

           Logistic  SVMl SVMNl  KNN Navie Decision Random
Kernal_PCA      0.5  0.49  0.45  0.5  0.49     0.57   0.53

In [65]:
result
#2

           Logistic  SVMl SVMNl   KNN Navie Decision Random
Kernal_PCA     0.45  0.49   0.5  0.56  0.48      0.6   0.55