In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [3]:
def selectlda(train_x, test_x, y_train,n):
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
    lda = LDA(n_components = n)
    #X_train = lda.fit_transform(X_train, y_train)
    train_x = lda.fit_transform(train_x,y_train)
    test_x = lda.transform(test_x)

        
        #test = SelectKBest(score_func=chi2, k=n)
        #fit1= test.fit(indep_X,dep_Y)
        #selectk_features = fit1.transform(indep_X)
    return train_x, test_x #lda_features

In [5]:
def split_scalar(indep_X,dep_Y):
        train_x, x_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        train_x = sc.fit_transform(train_x)
        test_x = sc.transform(x_test)    
        return train_x, test_x, y_train, y_test

In [7]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return classifier,Accuracy,report,X_test,y_test,cm

In [9]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return classifier,Accuracy,report,X_test,y_test,cm

In [11]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [13]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [15]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [17]:
def knn(X_train,y_train,X_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [19]:
def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion  = 'entropy',random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [21]:
def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [23]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['LDA'],columns=['Logistic','SVMl','SVMNl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        # df.loc[row_indexer, "col"] = values
        dataframe.loc[idex,'Logistic']=acclog[number]
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMNl']=accsvmnl[number]
        dataframe.loc[idex,'KNN']=accknn[number]
        dataframe.loc[idex,'Navie']=accnav[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
        # print(dataframe)
        # dataframe['Logistic'][idex]=acclog[number]       
       # dataframe['SVMl'][idex]=accsvml[number]
        # dataframe['SVMnl'][idex]=accsvmnl[number]
        # dataframe['KNN'][idex]=accknn[number]
        # dataframe['Navie'][idex]=accnav[number]
        # dataframe['Decision'][idex]=accdes[number]
        # dataframe['Random'][idex]=accrf[number]
    return dataframe

In [25]:

# Importing the dataset
dataset = pd.read_csv('Wine.csv')
df2=dataset.copy()
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [27]:

df2 = pd.get_dummies(df2, drop_first=True)
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [29]:
X = df2.iloc[:, 0:13].values
Y = df2.iloc[:, 13].values

In [31]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [33]:
train_x, test_x, y_train, y_test=split_scalar(X,Y)

In [35]:
n=len(set(y_train))
print("Number of Classes in target data",n)

Number of Classes in target data 3

In [81]:
X_train, X_test=selectlda(train_x, test_x, y_train,2)       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [83]:
X_train

array([[ 3.75722986e+00,  1.78224173e+00],
       [-3.71779979e+00,  8.55757484e-01],
       [ 4.41722893e-02, -2.02249034e+00],
       [-3.50295061e+00,  1.99910076e+00],
       [ 3.87566163e+00,  2.65077482e+00],
       [-3.31635950e+00,  7.26729526e-01],
       [-3.76757806e+00,  1.03585429e+00],
       [ 3.50642318e+00,  1.01134789e-01],
       [-5.56617679e+00,  2.31052117e+00],
       [ 5.52600002e+00,  6.92702501e-01],
       [-3.34933278e-01, -3.89801248e+00],
       [-4.83234812e+00,  3.19745682e+00],
       [-3.43511567e+00,  9.59123009e-01],
       [ 1.06452054e+00, -2.32005170e+00],
       [-3.47410738e+00,  6.35730414e-01],
       [-5.06710351e+00,  2.38898005e+00],
       [ 2.95021113e+00,  1.13904083e+00],
       [-1.87126516e+00, -4.32025549e-01],
       [-3.96376090e+00, -1.85802042e-01],
       [ 9.49159879e-01, -3.32074700e+00],
       [-1.84114933e+00, -5.83464878e-01],
       [-3.17380882e+00,  1.49403616e+00],
       [ 4.69174963e-01, -1.18843006e+00],
       [ 4.01401200e+00,  1.22643116e+00],
       [-2.41908539e+00, -2.41633744e+00],
       [ 1.19274638e+00, -2.30261770e+00],
       [-2.54081586e+00, -1.08324295e+00],
       [ 1.62865764e+00,  4.75402524e-01],
       [ 5.44639445e+00,  2.02327978e+00],
       [ 2.21713741e+00, -2.38188007e+00],
       [ 1.88880077e+00, -2.21613035e+00],
       [-5.47159839e+00,  1.51735664e+00],
       [-5.71896935e+00,  1.77938703e+00],
       [-1.21439339e+00, -3.90180089e+00],
       [ 1.10951972e+00, -3.10038781e+00],
       [-7.91493841e-02, -3.64486676e+00],
       [-5.07276956e+00,  2.58901991e+00],
       [-4.16583730e+00,  3.82003914e-01],
       [ 3.81161619e+00,  6.82242585e-01],
       [-5.15806933e+00,  2.18938472e+00],
       [ 7.05565940e-02, -3.12032063e+00],
       [-5.49782271e-01, -2.58183073e+00],
       [-4.81777377e-01, -1.94621769e+00],
       [ 9.47271531e-01, -2.69145221e+00],
       [-2.47677384e-01, -3.27442224e+00],
       [ 4.66412560e+00,  2.10417874e+00],
       [ 2.74657160e+00,  1.22618405e+00],
       [ 9.70323535e-01, -2.65613212e+00],
       [ 6.03529447e+00,  2.05320991e+00],
       [-4.27955550e+00,  1.22404709e+00],
       [ 3.56102240e+00,  3.64602762e-01],
       [-4.63713595e+00,  1.25794961e+00],
       [ 4.15399940e+00,  2.34532649e-01],
       [ 3.89495884e+00,  2.80806973e+00],
       [ 3.85565158e-01, -2.23125362e+00],
       [ 5.10121965e+00,  2.19942215e+00],
       [ 1.24482053e+00, -2.87881891e+00],
       [-1.40603770e-01, -2.74122412e+00],
       [ 4.94831045e+00,  3.60101959e+00],
       [-4.18699949e+00,  2.39822472e+00],
       [-4.12040856e-01, -2.02267161e+00],
       [ 5.09372053e+00,  2.90914396e+00],
       [-6.06902767e-01,  1.48754279e-01],
       [-1.18189699e+00, -2.82484745e+00],
       [ 6.04642183e-01, -2.10172486e+00],
       [-2.59531823e+00,  1.01090918e-01],
       [ 4.19739748e+00,  2.13715873e+00],
       [-5.12929171e+00,  5.84290625e-01],
       [-5.73804704e+00,  1.40897438e-01],
       [ 6.16151965e+00,  3.38985011e+00],
       [ 5.40944408e+00,  1.61438995e+00],
       [-1.40002502e+00, -2.52898156e+00],
       [-4.89726201e+00,  2.33040423e+00],
       [ 4.34535646e+00,  1.83689601e+00],
       [ 3.87338529e+00,  2.00056647e+00],
       [ 3.23778354e-02, -2.60462718e+00],
       [ 3.80595167e-01, -1.77179897e+00],
       [ 3.43965245e+00,  2.49051650e-02],
       [ 4.30472611e+00,  2.30750404e+00],
       [ 2.82799490e+00,  1.02297286e+00],
       [-4.24759571e+00,  3.48453506e+00],
       [ 1.04157594e+00, -1.35398866e+00],
       [ 4.90243969e+00,  1.17493343e+00],
       [ 1.55623962e+00, -2.18578346e+00],
       [-3.24771691e+00,  1.16098759e+00],
       [ 5.49376373e+00,  2.29563008e+00],
       [ 6.66169522e-01, -2.63422660e+00],
       [-4.05102186e+00,  1.41372952e-01],
       [-4.62722563e+00,  2.48805918e-03],
       [ 3.73008060e+00,  1.55110411e+00],
       [ 3.36731781e+00, -1.33149760e-01],
       [-4.14137298e+00,  4.82025770e-01],
       [ 4.06277298e+00,  2.92750009e+00],
       [-4.20381962e+00,  9.27890525e-02],
       [-2.34299794e-02, -3.76267700e+00],
       [ 3.23283004e+00,  1.33740625e+00],
       [ 4.01172391e+00,  8.43188286e-01],
       [ 4.84632761e-01, -2.74258911e+00],
       [ 4.34777396e+00,  2.21893150e+00],
       [-4.44247788e+00,  1.96593033e+00],
       [-9.98121758e-01, -3.05514439e+00],
       [-4.88170752e+00,  1.16732643e+00],
       [ 3.70161805e+00,  2.40654674e-01],
       [-3.43476601e+00,  9.77510494e-01],
       [-4.31507993e+00,  1.75850675e+00],
       [-4.73718654e+00,  2.26409768e+00],
       [ 3.47148953e+00,  9.35839032e-01],
       [ 1.52966148e+00, -3.71309507e+00],
       [-4.16342421e-01, -2.95146044e+00],
       [ 6.40748609e-01, -2.42607076e+00],
       [ 1.57941293e-01, -5.76604933e+00],
       [-5.05146408e+00,  1.89983827e+00],
       [-5.60153152e+00,  2.87029835e+00],
       [-4.72130781e-01, -1.63912574e+00],
       [-9.41821351e-01, -1.57478657e+00],
       [ 2.47826253e+00,  3.66222939e-02],
       [ 2.19029985e+00, -1.56623624e+00],
       [-4.81200781e+00,  2.26842207e+00],
       [-5.04448985e+00,  2.80590850e+00],
       [ 3.72739441e+00,  2.30551011e+00],
       [ 4.44451381e+00,  2.26536318e+00],
       [-2.81222081e+00,  1.07814395e+00],
       [-3.32507897e-02, -1.94457932e+00],
       [-1.36869831e+00, -8.44875564e-01],
       [-2.83727687e-01, -3.31942191e+00],
       [ 3.11785783e+00,  1.52018276e+00],
       [ 2.11030772e+00,  6.65330348e-01],
       [ 4.19830759e+00,  1.38813629e+00],
       [-1.78310181e+00, -3.79508000e+00],
       [ 8.22863399e-01, -2.68820697e+00],
       [ 1.11343805e-01, -3.65200649e+00],
       [ 4.12626825e+00,  7.27352760e-01],
       [-4.41071788e+00,  3.01534038e+00]])

In [85]:
X_test

array([[ 3.81260158,  1.42768022],
       [-5.21048071,  1.69416574],
       [ 0.48912124, -3.3931783 ],
       [ 2.11280014,  0.86466433],
       [ 0.18861347, -1.3043133 ],
       [ 4.96821244, -2.33039876],
       [ 4.82442302,  2.9027888 ],
       [-5.50222966,  0.86073107],
       [ 1.1848033 , -2.41061817],
       [-0.64541546, -2.33949018],
       [-2.26869621,  1.72936647],
       [-4.97841089,  1.90056168],
       [ 5.20565649,  3.17078798],
       [ 2.45294044, -2.64942247],
       [-4.24871686,  2.05909187],
       [ 0.5284542 , -4.69082892],
       [ 4.05483725,  1.79532273],
       [ 6.42019493,  3.82383717],
       [-2.42567193, -1.08146037],
       [ 5.04345481,  1.83331459],
       [ 2.32097763, -2.80635325],
       [ 2.40944434,  0.95645842],
       [ 1.75810849,  0.34503493],
       [ 1.37437851, -2.47069367],
       [-1.15314017, -0.96468356],
       [-0.3729784 , -2.8373037 ],
       [ 0.99808675, -2.71329767],
       [-0.97235656, -3.34078227],
       [ 0.93449044, -0.59379071],
       [-4.72918786,  2.04684377],
       [ 4.64417178,  2.13598551],
       [ 3.34360227,  1.38376075],
       [-1.06466164, -1.08031311],
       [ 3.22113427,  2.80021804],
       [ 4.22014689,  1.75818196],
       [ 3.08443072, -0.47390734],
       [-3.4147405 ,  1.86402109],
       [-0.97295759, -2.00635492],
       [-0.69901222, -3.15737219],
       [-4.69194652,  1.95287508],
       [ 3.80191411, -0.02524806],
       [ 3.43022665,  1.09035402],
       [ 0.48955259, -3.13982966],
       [-0.08926039, -2.45807002],
       [-1.2010709 , -3.38788916]])

In [87]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [89]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [91]:
result
#2

    Logistic      SVMl SVMNl       KNN     Navie  Decision    Random
LDA      1.0  0.977778   1.0  0.977778  0.977778  0.977778  0.977778

In [79]:
result
#1

     Logistic      SVMl     SVMNl       KNN     Navie  Decision    Random
LDA  0.866667  0.866667  0.844444  0.866667  0.866667  0.933333  0.911111