In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [3]:
def selectPCA(train_x,test_x,n):
    from sklearn.decomposition import PCA
    pca = PCA(n_components = n)
    train_x = pca.fit_transform(train_x)
    test_x = pca.transform(test_x)
    explained_variance = pca.explained_variance_ratio_

    return train_x, test_x #lda_features

In [5]:
def split_scalar(indep_X,dep_Y):
        train_x, x_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        train_x = sc.fit_transform(train_x)
        test_x = sc.transform(x_test)    
        return train_x, test_x, y_train, y_test

In [7]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return classifier,Accuracy,report,X_test,y_test,cm

In [9]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return classifier,Accuracy,report,X_test,y_test,cm

In [11]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [13]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [15]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [17]:
def knn(X_train,y_train,X_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [19]:
def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion  = 'entropy',random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [21]:
def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [23]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMNl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        # df.loc[row_indexer, "col"] = values
        dataframe.loc[idex,'Logistic']=acclog[number]
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMNl']=accsvmnl[number]
        dataframe.loc[idex,'KNN']=accknn[number]
        dataframe.loc[idex,'Navie']=accnav[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
        # print(dataframe)
        # dataframe['Logistic'][idex]=acclog[number]       
       # dataframe['SVMl'][idex]=accsvml[number]
        # dataframe['SVMnl'][idex]=accsvmnl[number]
        # dataframe['KNN'][idex]=accknn[number]
        # dataframe['Navie'][idex]=accnav[number]
        # dataframe['Decision'][idex]=accdes[number]
        # dataframe['Random'][idex]=accrf[number]
    return dataframe

In [25]:

# Importing the dataset
dataset = pd.read_csv('Wine.csv')
df2=dataset.copy()
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [27]:

df2 = pd.get_dummies(df2, drop_first=True)
df2

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

In [29]:
X = df2.iloc[:, 0:13].values
Y = df2.iloc[:, 13].values

In [31]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [33]:
train_x, test_x, y_train, y_test=split_scalar(X,Y)

In [71]:
X_train, X_test=selectPCA(train_x,test_x,6)       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [73]:
X_train

array([[ 2.12849974e+00,  1.01973208e+00, -8.26209888e-02,
         6.78090471e-01,  4.27091942e-01, -1.53118356e+00],
       [-2.94812519e+00,  2.54806705e-01, -1.14589113e+00,
        -5.97968964e-01, -5.18370178e-01,  1.06172459e+00],
       [ 1.91979542e+00, -1.33701156e+00,  4.02244683e-01,
         7.07416420e-01,  4.58701327e-02, -3.27511574e-01],
       [-2.13337607e+00,  9.45897150e-01, -1.40277015e+00,
         1.39579872e+00,  6.91567767e-01, -6.01101659e-01],
       [ 2.23680281e+00,  2.26983910e+00,  8.77499126e-01,
         4.36801265e-01, -9.58293769e-01,  1.28107783e-01],
       [-2.28747076e+00,  1.99359253e-01, -7.97227232e-01,
         1.23396178e+00, -3.50435082e-01, -1.03789452e+00],
       [-2.97244958e+00,  2.96522642e-01, -9.31504047e-01,
        -1.06705468e+00, -1.98434785e-01, -1.11183437e-01],
       [ 2.61809796e+00,  7.76070011e-01, -8.30660247e-02,
         2.24081998e-01,  7.26156222e-01,  6.74603563e-01],
       [-1.04705463e+00,  3.49093326e+00,  1.29203589e+00,
        -8.95933972e-01,  5.71604442e-01,  2.74880880e+00],
       [ 2.60981596e+00, -7.34569695e-02, -1.78959140e-01,
        -4.93030107e-01, -3.51200413e-01, -8.63561180e-01],
       [ 1.52296770e-01, -2.31809388e+00, -4.97096689e-01,
        -1.74771014e-01,  1.09716097e+00,  9.54049172e-01],
       [-2.61422416e+00,  2.54812754e+00, -1.05342808e+00,
         1.15586323e+00,  7.53802743e-01,  1.53161293e-01],
       [-2.50949512e+00,  4.27708661e-01, -9.04277766e-01,
         4.92203896e-01,  4.36934074e-01, -3.43220973e-01],
       [ 1.72319479e+00, -9.11994596e-01,  2.15447686e+00,
        -7.89444047e-01, -6.88933846e-01, -5.61282180e-01],
       [-2.75936377e+00,  3.86681070e-01,  7.50384226e-01,
         8.32308706e-02, -6.67156756e-01,  1.36328625e-01],
       [-2.82343185e+00,  1.89597038e+00, -6.34846718e-01,
        -8.99147136e-01,  1.04406629e+00,  1.29183551e-01],
       [ 1.36403459e+00, -8.54516419e-02, -1.31834921e+00,
        -3.98394943e-01, -7.58350784e-01, -5.28527538e-01],
       [-2.43383713e+00, -1.15738021e-01,  5.21582671e-01,
        -1.22427772e+00,  6.88803872e-01,  3.63743125e-01],
       [-2.25731631e+00, -4.86291422e-01, -1.08346105e+00,
        -9.28985662e-01, -7.53868550e-01,  1.59176473e+00],
       [ 1.12118381e+00, -2.51095575e+00, -1.03269867e+00,
        -5.67232658e-01,  2.88471378e-01,  2.81870260e-01],
       [-2.30339155e+00, -1.25712557e+00, -1.81677754e+00,
        -9.67312066e-01,  6.77464716e-01, -9.13345673e-01],
       [-2.50110791e+00,  5.37200019e-01, -9.35590700e-01,
         7.37249699e-01, -8.65711032e-02, -6.59909402e-01],
       [ 1.63810025e-01, -1.29094356e+00, -1.70710238e+00,
        -3.57134695e-01, -1.46207784e+00, -4.37492486e-01],
       [ 2.55406891e+00,  1.06285353e+00,  1.06007894e+00,
        -3.02103524e-01,  6.81399376e-01,  4.63992888e-01],
       [-7.67479380e-01, -3.08596417e+00, -4.57778471e+00,
         6.06126141e-02, -7.85171265e-01, -2.82236163e-01],
       [ 2.53386450e+00, -1.03476738e-01,  4.17588837e-01,
         3.94406022e+00,  8.52566491e-01,  1.94376216e+00],
       [-5.11862990e-01, -6.92471795e-01,  1.02474896e+00,
         3.54117070e+00, -5.10659352e-01, -7.01537365e-01],
       [ 5.38678361e-01,  3.23185656e-01, -1.29392154e-01,
        -1.73000271e-01,  1.39075634e+00, -1.15337842e+00],
       [ 3.55987441e+00,  1.34755387e+00, -3.01682342e-01,
        -3.05372675e-01, -1.56671133e-01, -9.25437403e-02],
       [ 1.61945680e+00, -1.47194770e+00,  1.73878945e+00,
         1.03953349e-01,  6.66255228e-01,  5.39879039e-01],
       [ 2.61872861e+00,  2.48743410e-02,  3.14971266e+00,
         2.33450965e+00, -6.74046255e-01, -1.61183092e-01],
       [-3.58075310e+00,  7.37740802e-01, -1.33383739e+00,
        -6.12862186e-01, -4.28155228e-01,  4.66256699e-01],
       [-1.58323537e+00,  2.39481792e+00,  6.55989860e-01,
        -1.05692438e+00,  4.23197534e-01,  2.37667920e+00],
       [ 1.44566293e+00, -1.42529469e+00,  1.02990216e-03,
         1.04696648e+00,  4.29436577e+00,  9.54771529e-01],
       [ 7.47885763e-03, -2.10807917e+00,  4.34324152e-01,
        -7.90477357e-01,  7.69709635e-01, -3.91811800e-01],
       [-1.55039574e-01, -2.87859455e+00, -3.58939023e-01,
        -7.49973464e-02,  3.93055635e-01, -1.06285877e-01],
       [-2.35609895e+00,  2.41121931e+00,  3.90792480e-01,
         6.06291857e-01, -9.75791639e-02,  4.21240178e-01],
       [-3.11008066e+00, -4.13464853e-01, -9.27581795e-01,
         4.74284449e-01, -1.35883947e-01, -5.13373990e-01],
       [ 3.25867129e+00,  2.77636807e-01, -1.85727554e+00,
        -4.87040260e-01,  1.17916532e+00,  8.53520305e-01],
       [-3.50784308e+00,  1.72550896e+00, -6.31012341e-02,
        -8.12728874e-01,  1.34364341e+00,  2.38397018e-01],
       [-4.30820213e-01, -2.64346544e+00,  9.05456433e-01,
        -1.44842774e+00, -5.40844334e-01,  6.24108291e-02],
       [-5.23573673e-01, -2.02939580e+00,  6.02489674e-01,
         4.55237576e-01, -1.76586927e+00,  3.03391313e-01],
       [-1.10965462e+00, -7.82761151e-01,  2.96486212e+00,
         1.75101064e-01,  1.13714339e+00, -1.10971195e+00],
       [ 1.00968727e+00, -1.37570996e+00,  1.55692094e+00,
        -5.94158796e-01,  3.57155869e+00, -8.26758913e-01],
       [ 1.98247419e+00, -1.70019796e+00, -1.58459202e+00,
         4.05742183e+00,  4.76681920e-01,  8.61472045e-01],
       [ 2.77325961e+00,  1.76838941e+00, -5.72095734e-01,
        -4.56109139e-01, -2.19017896e-01,  6.56027491e-01],
       [ 2.06945493e+00,  1.27720697e+00,  6.49410725e-02,
        -3.82642473e-01,  8.50973491e-02,  5.12916189e-01],
       [ 8.60586961e-01, -2.08160358e+00, -2.46203527e-01,
         2.40883307e-01, -7.45529820e-01, -2.77047513e-02],
       [ 3.51764429e+00,  1.34777921e+00, -8.78418958e-01,
        -1.93233071e+00,  1.19066402e-02,  1.06859812e+00],
       [-3.77996006e+00,  3.79211953e-02,  1.94122190e-01,
        -2.95558583e-01,  4.12593039e-02, -8.94042058e-01],
       [ 1.72749292e+00, -5.31649167e-01,  2.18838690e-01,
        -3.49519244e-01, -7.45466996e-01, -7.53686121e-01],
       [-3.42557047e+00,  7.98552067e-01, -3.73552626e-01,
        -7.97129902e-01,  3.31225803e-01, -3.81863535e-01],
       [ 3.14791384e+00,  7.38564002e-01, -3.21772613e-01,
         8.62351567e-01,  2.08543878e-01, -6.39325719e-02],
       [ 2.38109106e+00,  1.62455368e+00,  2.83755086e-01,
         1.02387172e-02, -1.56431127e+00, -2.20613795e-01],
       [ 1.28316687e+00, -9.53960701e-01, -1.44461270e+00,
         2.61250079e+00,  5.72316577e-01,  1.99040870e+00],
       [ 3.57366728e+00,  1.69259754e+00, -3.85401845e-01,
        -6.26427455e-01, -4.71389681e-03,  1.28391743e-01],
       [ 9.12058331e-01, -2.42502183e+00, -1.64492069e+00,
         2.41099103e-01,  2.39958266e-01, -2.51684062e-01],
       [ 4.67022319e-01, -2.13917446e+00, -2.38792838e+00,
        -3.10087307e-01, -2.31207584e-01,  3.30260558e-01],
       [ 3.81636400e+00,  2.81547840e+00, -1.90108115e-02,
        -3.91576515e-01,  2.19833024e-01, -9.79123742e-02],
       [-2.32677847e+00,  2.08857718e+00, -6.84905143e-01,
         1.00998196e+00, -1.61697633e-01,  1.26338688e+00],
       [-1.52142992e+00, -1.41178830e+00,  2.77168127e-01,
        -6.20841468e-01, -1.82842757e-01,  6.20024320e-01],
       [ 2.51818928e+00,  1.24415522e+00, -7.41901516e-01,
        -9.95609872e-01, -4.88150558e-01, -4.39046916e-01],
       [-6.77941655e-01, -3.09106140e-01, -7.12782419e-01,
         1.10747741e-02, -2.29175288e+00,  3.06390682e-01],
       [-7.66045456e-01, -2.54381100e+00, -1.68489993e+00,
         5.65347010e-01, -3.30681912e-01,  2.12236287e-01],
       [ 8.63649631e-01, -1.51546118e+00,  5.78233354e-01,
         5.68141741e-01,  6.22141193e-01,  4.54884453e-01],
       [-1.23880696e+00, -5.84272887e-02, -1.35693960e+00,
         2.42802191e+00, -1.08006063e+00, -2.83688642e-01],
       [ 2.21186398e+00,  7.53275628e-01, -6.84165776e-01,
        -1.11494398e+00, -8.00959838e-01, -1.56080418e-01],
       [-3.82956254e+00,  5.25700837e-01,  1.68655481e+00,
        -4.60358338e-01,  6.55805270e-01, -5.79607251e-01],
       [-1.76777879e+00,  1.31951728e+00,  1.24923998e+00,
         1.79196913e+00, -2.12136112e-01,  3.95798307e-01],
       [ 4.35873299e+00,  2.24834474e+00, -1.03118750e+00,
        -1.01898265e+00,  2.66642014e-01,  8.90110573e-01],
       [ 3.33591108e+00,  1.39194415e+00, -1.08125929e-01,
         7.41334540e-01,  2.67958241e-02, -7.73085017e-04],
       [-1.48478755e+00, -1.94049512e+00,  7.30151734e-01,
        -4.06464843e-01, -5.39982198e-01,  9.13297461e-01],
       [-2.70337927e+00,  2.06961390e+00, -9.48837331e-01,
        -6.08108756e-01,  9.20641538e-01,  1.69511147e+00],
       [ 2.79538972e+00,  1.28878345e+00, -3.11064774e-01,
        -8.52674547e-01,  1.11206341e+00, -9.97109703e-01],
       [ 1.85926517e+00,  6.32787608e-01, -1.03995852e+00,
        -5.56545536e-01, -1.29716894e+00, -3.97009373e-01],
       [-4.53905029e-01, -2.23873339e+00, -3.63397044e-01,
        -3.52467899e-01,  1.53147937e+00, -5.18062607e-01],
       [-8.32479410e-02, -1.23099611e+00,  9.93664505e-01,
         5.87789438e-03,  4.90560850e-01, -8.27434453e-01],
       [ 1.97449797e+00,  1.68734109e-01,  5.24718178e-01,
        -2.75599481e-01, -7.70888957e-02, -3.25689113e-01],
       [ 2.25985213e+00,  1.23442885e+00,  3.49558631e-01,
        -4.77055385e-01, -7.50391036e-01, -2.46126278e-01],
       [ 7.89323623e-01,  2.01746663e-01, -6.70089718e-01,
        -8.20962776e-01,  8.89353919e-01, -1.47233214e+00],
       [-3.27020912e+00,  2.13610115e+00, -2.34426780e-01,
        -7.37677508e-01,  8.71502502e-01, -1.05119755e+00],
       [ 9.60092676e-01, -7.83549614e-01,  5.58249705e-01,
         2.54439770e-02, -4.78201019e-01,  1.04108974e+00],
       [ 2.30520847e+00, -2.94658283e-01, -1.91871965e+00,
        -4.26019825e-01, -3.63921217e-01, -8.38094890e-01],
       [ 8.11817077e-01, -1.44079738e+00,  1.04923537e+00,
        -1.54619057e-02,  1.24394583e+00, -2.24649654e-01],
       [-2.26440851e+00,  4.44178294e-01, -1.10393843e-01,
        -7.79258742e-01,  4.83129916e-01, -1.32830520e+00],
       [ 3.13752247e+00,  1.22442962e+00, -1.26993578e-01,
        -5.02294826e-01, -1.98795954e-02, -1.13046260e+00],
       [-1.67949916e+00, -1.78087335e+00,  9.17954756e-01,
        -1.07073500e+00,  3.43750275e-01,  4.87836107e-01],
       [-2.82728701e+00,  6.90443617e-02, -2.75788311e-01,
         1.03936636e+00, -6.65092365e-01, -5.26526214e-01],
       [-2.65197806e+00,  2.49692065e-01, -1.33036547e+00,
         4.74995034e-01, -2.84121481e-01,  1.81644358e+00],
       [ 1.97882761e+00,  1.59155072e+00,  8.11730036e-01,
         3.91051152e-03, -1.10979368e+00,  5.42494732e-01],
       [ 1.61795568e+00, -7.66703464e-01, -1.38910938e+00,
        -1.65362744e-01, -7.81369663e-01, -2.84134132e-01],
       [-2.03958713e+00,  1.89317723e-01, -5.45846408e-01,
         1.51355312e+00,  7.22170606e-03, -1.44722526e+00],
       [ 2.30154259e+00,  1.84752991e+00,  4.04114372e-01,
        -1.00450632e-01, -1.18458519e+00,  1.18082900e-01],
       [-2.26940785e+00,  1.57815407e-01,  1.22911024e+00,
        -1.34895474e-01, -8.25072769e-01, -1.77865706e-01],
       [-3.91743210e-01, -1.97595383e+00,  1.25806180e+00,
        -3.24927600e-01,  5.20099156e-01,  4.89133009e-01],
       [ 1.49041281e+00,  6.25473436e-01,  5.07920090e-01,
         4.24898693e-01, -1.15709256e+00, -5.09310063e-01],
       [ 2.24738714e+00,  6.88073889e-01,  1.52714123e+00,
        -4.38259399e-01, -1.01923134e+00, -2.97580821e-01],
       [-3.89140329e-01, -1.96394119e+00,  1.33274104e+00,
        -9.17268934e-01, -4.92012114e-01, -1.61117092e-01],
       [ 2.76957033e+00,  1.46161853e+00, -2.99332694e-01,
         7.55335957e-03, -5.74649272e-01,  5.44114282e-02],
       [-2.82921453e+00,  1.83350745e+00, -6.16871949e-01,
         1.22949488e+00,  6.13277935e-01, -2.80783273e-01],
       [-1.50730937e+00, -1.31749083e+00,  3.23438521e+00,
        -3.70098283e-01, -2.35654619e-01,  9.81108388e-01],
       [-3.28214353e+00,  1.14390897e+00,  1.49663428e+00,
        -3.40610024e-01, -5.27733980e-01,  9.09163393e-01],
       [ 1.70930763e+00,  5.87536905e-02, -8.81691239e-02,
        -3.96107991e-01, -6.31953850e-01,  3.99064771e-01],
       [-2.87703277e+00,  3.45785464e-01,  1.00228553e+00,
        -2.09419733e-01, -1.36834717e+00, -9.19696653e-01],
       [-2.27186276e+00,  2.09219986e+00,  2.92852806e-01,
         2.20213111e+00, -6.66415238e-03, -4.90266051e-01],
       [-3.47678381e+00,  1.18758425e+00, -5.28476790e-02,
        -7.88172573e-01,  6.65261212e-01, -8.66782040e-01],
       [ 2.32543116e+00,  2.44337783e-01, -9.07661298e-01,
        -6.80216354e-01, -4.20945562e-02, -3.05550745e-01],
       [ 1.46611705e+00, -2.06782916e+00,  8.28576088e-01,
        -1.02563763e+00,  1.58378984e+00,  8.45743636e-01],
       [-3.82761857e-01, -2.41793363e+00,  1.34902983e+00,
        -7.93236565e-01, -1.37914078e+00,  2.83619228e-01],
       [ 4.50163506e-01, -1.05312379e+00,  1.81343532e+00,
        -3.30409126e-01,  1.09568677e+00, -4.61747826e-01],
       [ 5.72776083e-01, -3.88076632e+00,  1.25983243e+00,
        -7.61157509e-01, -4.10834866e-01,  1.47531370e+00],
       [-2.71728029e+00,  1.49037448e+00, -4.24242969e-01,
        -4.44559245e-01,  3.46942280e-01,  2.24702841e-01],
       [-3.13804648e+00,  2.68476716e+00,  1.13739684e+00,
        -8.09134930e-01,  1.83602462e-01,  1.71116737e-01],
       [-6.14506699e-01, -1.12400443e+00,  1.47266309e-01,
        -3.32175843e-01, -7.45375368e-01, -7.86074657e-01],
       [-1.36227447e+00, -1.56046239e+00, -3.93923912e-01,
         1.06003204e+00, -8.17789419e-02, -4.90083039e-01],
       [ 1.02517955e+00,  7.79778193e-01,  3.74343107e+00,
         8.72528208e-01, -1.11938060e+00,  2.04429974e-01],
       [ 1.12122140e+00, -1.43499022e+00, -2.97410863e-01,
        -5.62676422e-01,  2.62095480e-02, -2.43784101e-01],
       [-2.84028822e+00,  1.17419974e+00, -1.18907599e+00,
        -4.60033175e-01,  3.58877937e-02,  3.20809851e-04],
       [-2.32603653e+00,  2.38615103e+00,  1.40541729e+00,
         1.07526184e+00,  3.05692733e-01, -1.40604276e+00],
       [ 2.54215407e+00,  1.77306082e+00, -2.22585979e-01,
         9.43172206e-01,  1.42614258e+00, -1.55615671e+00],
       [ 3.20902540e+00,  1.76888456e+00, -1.99304758e-01,
        -4.62375937e-03, -6.23336682e-02, -1.51933136e-02],
       [-2.68218112e+00,  1.52829339e-01,  6.30287868e-01,
        -2.61619231e-01, -1.02690717e+00, -4.50201967e-01],
       [-1.00468497e+00, -1.85934423e+00,  9.06773693e-01,
        -6.75601904e-01, -3.83321797e-01,  2.05279067e-01],
       [-1.46565835e+00, -1.05942947e+00, -7.92758050e-01,
         1.11742937e+00, -7.78221494e-01,  4.69259379e-01],
       [-4.65414906e-01, -2.48932490e+00,  2.23077357e+00,
        -1.94012385e-01, -1.19205186e+00, -1.91536531e-02],
       [ 1.44880978e+00,  6.16727082e-01,  5.23184645e-01,
         1.90248070e-01, -1.30496557e+00, -4.09457135e-01],
       [ 1.12753462e+00,  2.06646534e-01,  1.01829765e+00,
         6.27506297e-02,  9.23170392e-01, -1.28141009e+00],
       [ 2.81765565e+00,  8.45873554e-01, -8.28612667e-01,
        -6.90810459e-01, -1.01553482e-01, -1.26548812e-01],
       [-5.40398126e-01, -2.69352638e+00, -8.11081189e-01,
        -3.03555223e-01,  5.65140445e-01,  3.18275859e-01],
       [ 2.94211054e-01, -2.43046262e+00, -1.02345021e+00,
        -9.34137804e-01, -3.68802428e-01, -3.57026542e-01],
       [-3.31843557e-02, -2.06611350e+00,  5.63365366e-01,
         9.56918037e-01,  7.73929959e-03,  1.03170405e-01],
       [ 2.88689907e+00,  7.14086057e-01, -1.02305264e+00,
        -4.33347623e-01,  6.98064017e-01, -5.70550927e-02],
       [-2.39279562e+00,  2.13222190e+00, -7.77386482e-01,
        -6.98073701e-01, -4.66501693e-01,  4.01896778e-01]])

In [75]:
X_test

array([[ 2.21435735,  0.94903218, -0.95228447,  0.78791127, -0.22041183,
        -0.4583446 ],
       [-2.50659973,  1.8189127 , -0.45680555,  1.58958192,  0.37747294,
         0.1455683 ],
       [ 2.12730524, -1.84889911,  0.06650656, -0.53349371,  0.4309516 ,
         0.23630369],
       [ 2.50886727,  1.2717395 ,  0.51542137,  0.84228632,  0.28537278,
         0.34043017],
       [-0.37546624, -0.56631262,  0.61477967, -0.89497518,  3.24197341,
        -1.91368411],
       [ 1.36750624,  0.10407461,  5.10950965,  0.49922603,  0.25264942,
         0.48860676],
       [ 2.13754395,  1.51780749,  0.19823085,  0.44985117, -1.27817566,
        -1.0496848 ],
       [-3.03876331,  0.67608136, -0.08506826, -0.70573647,  0.82904107,
         0.055545  ],
       [-0.2758078 , -2.17934109, -0.46001318, -0.79218027,  0.21777133,
         0.1059821 ],
       [-1.25059924, -2.13272889, -0.03829563, -0.8410568 , -0.33534478,
         0.78223271],
       [-2.17229537,  0.26937194, -0.90079853, -0.37203801, -0.85762617,
        -0.95888372],
       [-4.15065395,  0.59248433, -1.29975265, -0.75852251,  0.59615668,
        -1.77828428],
       [ 3.13110267,  2.16664974, -0.51087192, -0.41052281, -0.58379615,
         0.28647975],
       [ 2.34763044, -1.34053226, -0.19375446, -0.70818981,  0.6641495 ,
         0.49938741],
       [-2.12507456,  1.90448753,  0.74612768,  0.56528037, -0.57050596,
         0.43456629],
       [ 0.85556305, -3.3777156 , -0.35789025, -0.38500383, -0.39092563,
         0.21328297],
       [ 1.98167335,  1.50511222,  1.11634483,  0.64148574, -1.950769  ,
         0.42402287],
       [ 3.63741938,  2.5736509 , -0.36983498, -0.7752159 , -1.18018517,
         0.40269084],
       [-1.71186491, -0.91640251, -1.67018104, -0.13518066, -1.1637269 ,
         0.88059207],
       [ 2.9164406 ,  0.79680399,  0.18037953, -0.64702891, -0.63267771,
        -0.17668781],
       [ 2.3249174 , -1.72571959, -1.86452029, -1.46588161,  1.12056372,
         0.85429622],
       [ 1.22396251,  0.09218019,  0.00894161, -0.10545561, -1.14893586,
        -0.322939  ],
       [ 1.05405671,  0.77761047,  2.02201121,  0.58148521, -0.26942024,
        -0.20623022],
       [ 0.49794728, -2.11185944, -0.44455377, -0.67415805,  0.16931252,
        -0.30323978],
       [-1.39881137, -1.47214981, -0.93982111, -0.29954349, -2.42477948,
         0.83406749],
       [-0.17018683, -1.94392077,  0.11015206, -0.23145102,  0.58600517,
        -1.02159947],
       [ 0.12502046, -1.24129108,  0.69631084, -0.81431482,  0.93707252,
         0.47337602],
       [-0.70432191, -2.31220489,  0.71108338, -0.09185929, -0.88373742,
         0.62285977],
       [-1.2181713 , -0.89791369,  1.89838048, -0.0923968 , -1.36433324,
         0.12569465],
       [-2.8592085 ,  1.4495579 , -0.91738673, -0.43571846, -0.43577829,
         0.16834093],
       [ 1.87302687,  0.73992335,  0.06005344, -1.04860117, -0.71021915,
        -0.55423687],
       [ 2.78693593,  1.43073775, -0.51988279,  0.30508026,  0.19792336,
         0.03512482],
       [-1.67370951, -1.1675506 ,  0.81067708, -0.92493393,  1.21121302,
        -1.11443664],
       [ 1.22958376,  1.74681995,  0.15251989, -0.20334821,  0.35324093,
        -1.85234836],
       [ 2.59363119,  1.02863962, -1.5196656 , -0.98260706, -0.2984916 ,
        -0.06005794],
       [ 2.16840055, -0.07169437, -0.64718168,  0.0904908 ,  0.83601049,
         0.17599452],
       [-2.14365941,  1.04223426, -0.05723024,  0.10536167, -1.12053582,
        -0.39952566],
       [-1.82383615, -1.58240103, -0.07005641, -1.06279229, -0.54528815,
         1.18167987],
       [ 1.03058102, -2.26422887,  0.10697974,  0.54527405,  0.36632608,
        -0.74062143],
       [-2.51677592,  1.62600691,  0.20943381,  0.23078443,  0.29631977,
        -0.12178819],
       [ 1.82982474, -0.32052431,  1.02087063, -0.52025194, -0.59355777,
        -0.83769803],
       [ 2.57271699,  1.25647727,  1.46910242, -0.33288142, -0.70405803,
         0.55377316],
       [ 0.80536236, -2.29093724,  0.18982691, -0.28761586,  1.21684878,
        -0.68357275],
       [-0.44263058, -2.35561985, -1.51126717,  0.05790153, -0.34342888,
        -0.14062036],
       [-0.363284  , -2.3174417 ,  0.98114094, -0.20768377, -0.78167265,
         0.94683489]])

In [77]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [79]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [83]:
result
#6

    Logistic      SVMl SVMNl       KNN Navie  Decision    Random
PCA      1.0  0.955556   1.0  0.977778   1.0  0.977778  0.977778

In [69]:
result
#5

     Logistic      SVMl SVMNl  KNN Navie  Decision    Random
PCA  0.977778  0.955556   1.0  1.0   1.0  0.977778  0.977778

In [57]:
result
#4

     Logistic      SVMl     SVMNl       KNN Navie  Decision    Random
PCA  0.977778  0.955556  0.977778  0.955556   1.0  0.977778  0.911111

In [45]:
result
#3

     Logistic SVMl SVMNl  KNN Navie  Decision    Random
PCA  0.977778  1.0   1.0  1.0   1.0  0.955556  0.955556